### ISSUE TITLE
Attachments formatting problem

### ISSUE THREAD

**Issue by draustin** [exomut/evernote-dump#12]
Thanks for this fantastic tool. I converted a large notebook with only one small hitch. The ATTACHMENTS section has two lines per attachment. The first is the usual markdown reference i.e. [<reference>]: <file>. The second line is contains the same information but reads [<reference>](file).  For example, this note contains two image files:'improved_offline_processing.png' and 'improved_offline_processing-2.png'. The generated Markdown is:

```
### ATTACHMENTS
[12a0de4335818a8f266a492c4eab72fe]: media/Improved_offline_processing.png
[Improved_offline_processing.png](media/Improved_offline_processing.png)
[5537d1bc36ecb0c0985108ae92173f43]: media/Improved_offline_processing-2.png
[Improved_offline_processing-2.png](media/Improved_offline_processing-2.png)
```
This doesn't render. If I delete the []() lines then it works fine.

**Comment by exomut** [comment]
I tried to recreate the issue without success. Evernote Dump prevents overwriting extracted data by adding a number to the end of the file. From the looks of it, there must be 2 images with the same name and contents embedded in the enex file.
