### ISSUE TITLE
Failed on saving files with attachments due to special chars in filenames (OSError 22)

### ISSUE THREAD

**Issue by iwyatt** [exomut/evernote-dump#14]
Main.py error due to bad file name in note.py line 193 OSError 22

Bad file name included attachment with special characters (:` etc)

For my purposes, I fixed by using regex to strip all non alpha-numeric characters.

In note.py:

Changed from: 
```
    def create_file(self):
        # Create the file and set the original timestamps
        __path = os.path.join(make_dir_check(os.path.join(self.__path, self.__MEDIA_PATH)), self.__filename)
        with open(__path,'wb') as outfile:
            outfile.write(self.__rawdata)
        os.utime(__path, (self.__created_date.timestamp(), self.__created_date.timestamp()))
        self.__rawdata = ""
```

to:
```
    def create_file(self):
        # Create the file and set the original timestamps
        self.__filename = __path = re.sub(r'\W+', '', self.__filename) ### strip non-alphanumeric characters
        __path = os.path.join(make_dir_check(os.path.join("r",self.__path, self.__MEDIA_PATH)), self.__filename)
        with open(__path,'wb') as outfile:
            outfile.write(self.__rawdata)
        os.utime(__path, (self.__created_date.timestamp(), self.__created_date.timestamp()))
        self.__rawdata = ""
```

Probably not an adequate solution for most, so not submitting a proper pull request, but leaving here in case its an appropriate solution for someone else.

**Comment by exomut** [comment]
Thank you for taking the time to report this issue. Before forcing only alphanumeric I am going to try replacing troublesome characters, since many users have filenames with foreign language characters in them.

Let me know if you run into anymore problems.
