### ISSUE TITLE
Cannot concat str to bytes

### ISSUE THREAD

**Issue by jwesolo** [exomut/evernote-dump#18]
Hello,

Thank you for writing this package. In attempting to convert some ENEX files, I kept running into a problem with append_html () in note.py (line 54). After processing some lines, at some point self._html becomes a bytes object instead of a string. Thus, the '+' operator would not work. I put this in as a quick workaround as I did not have time to track down where self._html was getting converted to bytes:

    def append_html(self, text):

        if isinstance (self._html, (bytes, bytearray)):
            self._html = self._html.decode ('utf-8')

        self._html += text

Thanks again for providing this package!

**Comment by exomut** [comment]
Thank you for your comment. This issue has been solved by @octplane and I have merged in the pull request.
