### ISSUE TITLE
File naming problems

### ISSUE THREAD

**Issue by jgclark** [exomut/evernote-dump#19]
I'm trying to run this on both a single file and a folder exported today from Evernote (v10.3.7) on macOS 10.15.7.
Both have issues:

1. The content of the generated .md files seems to be fine, but the filenames are all of the form `_1f1978ba-6c88-409c-aece-c418521deeb7` which aren't exactly going to make retrieval easy.

2. The H1 title of the generated file is just this same UUID. In the cases I've checked so far, this has removed the note's existing title.

3. The content of the images and PDFs in the /media folder again seem to be fine, but the filenames are all of the form `________-396.unknown`, which means I can't view them on their own.  This is with or without the -p flag.

If these are expected behaviour, then please instead treat this as feature request not a bug report. Thanks.

PS Not being fluent in python, I couldn't work out how to run your script from the command line. Do I have to alter PATH or otherwise install the code in some way?

**Comment by exomut** [comment]
Thanks for getting in touch!

Getting UUIDs as file names and `.unknown` as an extension means that python was unable to discover the file type. If it is occurring with the `-p` flag as well, that means your exported Evernote file does not have the file names included.

Does this happen will all of the parsed `*.md` files and attachments?

Another thing to check is if there is a problem in the exported `*.enex` file. Open the file in a text editor and search for `<title>`. Search through the file and check to see if all the titles are correct in the file.

To run from the terminal:

```Bash
# change to the directory containing the evernote_dump folder and run:
python -m evernote_dump -p path/to/file.enex

# or for the GUI
python -m evernote_dump
```

I will leave the issue as open, since this may be a problem with a new version of Evernote's exported `.enex` files.

**Comment by jgclark** [comment]
Thanks for quick reply, @exomut!
Yes, none of the .md files have a sensible filename.
I've checked the .enex files, and I see a correct `<title>...<\title>` tag for the main note.
For the embedded images I see `<mime>image/jpeg</mime>` but they have `<file-name></file-name>` empty.
For an embedded PDF I see `<mime>application/pdf</mime> ... <file-name>improve_your_cutting_2012.pdf</file-name>`.

So even if the .enex format has changed, all of the information I'm after is still there. (It doesn't matter about embedded image file names.)

**Comment by exomut** [comment]
Thanks for taking the time to help me resolve this issue!

There are 2 things I would like you to try:

1) Run the Unit Test and Check if all 4 tests pass:

```Bash
# Run from the directory containing the `evernote_dump` folder

python -m unittest
```

2) Try to parse one of the included sample `.enex` files:

Included in the directory that contains the `README.md` file, there is a folder named `data`. Inside there are 3 sample `.enex` files. Try to convert one or two of those and see if the output looks strange.

If either or both of the 2 steps have an issue, then there might be something not set up correctly on your machine; such as Python/module version issues.

However, if both steps succeed, it is an issue with the newer version of `.enex` files or evernote_dump and it might take some time to fix.

**Comment by jgclark** [comment]
Thanks.

1. I ran the Unit tests and it reported that 4 ran OK.

2a. Parsing Archives.enex seemed to be fine. Though I noticed one resulting .md file had a strange filename and title: "s Food Cures Light Balsamic Vinaigrette". Turns out from inspection of the enex it got truncated at an `&apos` character in the `<title>` tag.

2b. Parsing the other .enex files produced just the same files as Archives? (and the same problem)

So it does look like there's a recent change in the Evernote exports.

**Comment by exomut** [comment]
I just downloaded the newest version of Evernote and made a new export of my notes. After testing with the newly exported file I ran into the same error as you. It looks like Evernote made a lot of changes to the `.enex` file. They also put a limit of 50 files at a time for exporting! The old version allowed all notes to be exported at once.

I was able to find a legacy version of Evernote on their official site. [Legacy Evernote](https://help.evernote.com/hc/en-us/articles/360052560314-Install-an-older-version-of-Evernote) (Mac and Windows versions are available.)

Using that version of Evernote works. I will update the `README.md` for the evernote_dump project to inform people to use that. I think fixing evernote_dump to work with the newer version would be quite time consuming and may break some features.

Thank you for putting so much time into figuring this out with me! I will be closing the issue for now. If you feel like it is still not working correctly. Please open another issue.
