### ISSUE TITLE
Export attachments using the note title as the filename

### ISSUE THREAD

**Issue by tnaseem** [exomut/evernote-dump#20]
Great app, which I'm currently using to export all my notes, which are mostly made up of notes with inline PDFs, as a document store.

A lot of these PDFs have their original filenames which don't match the note (eg. dated grabs, etc). So I was wondering if there's a possibility of adding an option to use the Note title as the filename (+ original extension)?

**Comment by tnaseem** [comment]
Ok. I've done a quick hack to get me by, by adding the following to the try block in `note_parser.py`:

```
    self.attachment.set_filename(self.note.get_title())
```

and forcing the filename to use the same in `create_filename` in `attachment.py`:

```
    self._filename += '.' + extension
```

Very ugly, but it will work for me for now! :)

**Comment by jgclark** [comment]
Will this “hack” work with multiple attachments or web pages with multiple images embedded in it?

**Comment by tnaseem** [comment]
Yes, it will work with multiple attachments, as the code takes care of this anyway (adding a sequence number).

As for web pages, it won't work, as the filenames would be different to what's in the HTML.

**Comment by exomut** [comment]
Thank you for taking the time to look into this. I have added the feature to the GUI and the command line interface.
