### ISSUE TITLE
Trying to track down how the `xml.sax` tooling is handling a particularly slow note with pdf attached.

### ISSUE THREAD

**Issue by Analect** [exomut/evernote-dump#5]
@exomut 
I know you weren't planning to spend more time on this repo at this point.  It's usage of this streaming XML approach has great promise for handling my 12GB+ evernote database/enex export, so I'm keen to solve some outstanding problems, but I have little experience in working with `xml.sax`.

The `Test_Agenda.enex` file attached below (I had to zip it for it to get attached on github) ... although just a single note with a few embedded images and a PDF attachment ... seems to be a real struggle for this tool and is taking up to 90 seconds to process and I'm trying to pin down what could be causing this ... as I have thousands of notes like these and ideally don't want to have each take so long to process.

[Test_Agenda.zip](https://github.com/exomut/evernote-dump/files/837845/Test_Agenda.zip)

Could you suggest what might be the problem here?  I have tested this on various machines, so I don't think the slowness is a machine resource issue.  I would have thought a circa 2MB PDF, even in base64 form, shouldn't be a problem for this tool, but I'm wondering is there something malformed in the PDF that is causing this problem.

Thanks.

**Comment by exomut** [comment]
I had noticed a similar problem in an earlier version. I was using a temp file to solve the issue, but moved away from using a temp file since my files were exporting reasonably quick.

I did some research and found out the quickest way to handle large string concatenation. [Efficient String Concatenation](https://waymoot.org/home/python_string/) I am still pretty new to python, so I don't know all of the tricks yet.

After switching to joining an array instead of "my_string += my_stream" evernote-dump is blazing fast on my end.

Give it a try and tell me how it goes. Thanks again for your feed back. I have thousand of attachments and notes that I am working on exporting as well.

I won't mark this issue as close until you reply.

**Comment by Analect** [comment]
That's a great improvement. Thanks.

Could I just ask one quick follow-on ... happy to put this in a separate issue, if necessary. 

I think your uses of classes etc.. is very good.  I hack about in python too but haven't managed anything as clean as this.  I find it more challenging to reason about things though.  Perhaps you could point me in the right direction.

I'm extending things such that I'm writing attachments and notes to database backends (rather than the file-system) and wanting to maintain a parent-child relationship between the note (parent) and attachments (children).  I'm looking to apply a unique identifier to each and want to re-use the parent identifier reference in the children documents.

I added a `self.__identifier = uuid.uuid4.()` in the class Note (see below).  And in order that I can then access this value in the Attachment object, I added a `def get_uuid` function and `identifier = getid.get_uuid()` outside both classes, so that the `identifier` is available to me for usage against the parent and children documents.  I was under the impression that each time a new `note` tag is found in the `enex` file, then a new note object is initialised, which would give me a new identifier, but that doesn't appear to be the case for an enex with multiple notes.

I played around, even trying to add `self.note.create_uuid()` in the evernote_dump.py .. which would then call a `create_uuid` function (moving the uuid.uuid4() out of initialisation and instead assigning it to self.___identifier in that function).  However, that didn't work at all.

pseudo-code:
```
class Note(object):
    def __init__(self):
....
        self.__identifier = uuid.uuid4()
....
    def get_uuid(self):
        return self.__identifier

    def send_note_somewhere(self):
        id=identifier                  #working for 1 note enex
        id=str(self.__identifier)  #ends up spawning a different uuid for parent note v identifier applied to children
....
....
class Attachment(Object):
    def send_attachment_somewhere(self):
        id=identifier

getid = Note()
identifier = getid.get_uuid()
```

Would you have a suggestion of how to best handle this?  Thanks again.

**Comment by exomut** [comment]
All of the getting and setting is done through evernote_dump.py , so you will need set the uuid for the attachments from there. I have been programming in Java a lot over the past couple of years. I am not sure if I am using python in a python way so it may be confusing.

I created a new branch called "uuid" to help explain. I also added uuid support really quickly. Please feel free to change it to meet your needs. [UUID Branch history](https://github.com/exomut/evernote-dump/commit/122fd5cbe85fe6489f685a8e9eb5a1407ecde15a)

I added some print statements for note.py to show that the UUID is being set.

I am going to mark the issue as closed. If you want to continue on this topic, please open another issue ;-)
