### ISSUE TITLE
Why can't this be run without internet? 

### ISSUE THREAD

**Issue by daljeetv** [exomut/evernote-dump#6]
What line is make url calls?
When I run with no internet connection I get:

<urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by exomut** [comment]
The code that I wrote does not require an internet connection, but I do use the [html2text](https://github.com/aaronsw/html2text) module. So I am guessing that may be the cause of your problem. html2text is parsing the evernote note from html into markdown.

I have no plans to continue developing this project, feel free to fork it and make it work for your personal needs.

**Comment by daljeetv** [comment]
Thank you @exomut . Nice work on the project!
