### ISSUE TITLE
It doesn't works even a english note

### ISSUE THREAD

**Issue by standin000** [exomut/evernote-dump#7]
[1]English [2]日本語 1
Would you like to keep the original filenames if found?[y/n] y
Evernote.enex was unable to be parsed correctly.

Thanks very much!

**Comment by exomut** [comment]
Sorry for the extremely late reply. I just got back on github a few weeks ago...busy with work. Excuses aside, I made some changes. I removed the try: except: catch all, so now errors will be more obvious. If you get around to testing it, let me know if it works. I completely understand if you don't. I will mark this as solved for now.
